name = "tpilzh"
version = "0.1.0"
defaultTargets = ["tpilzh"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "main"


[leanOptions]
#weak.verso.examples.suggest = true
linter.typography.quotes = false
linter.typography.dashes = false
weak.linter.verso.manual.headerTags = true

[[lean_lib]]
name = "TPiLZh"

[[lean_exe]]
name = "tpilzh"
root = "Main"
